name: duidku
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dots_indicator: ^3.0.0
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: 6.1.0
  page_transition: ^2.1.0
  intl: any
  collection: ^1.17.0
  calendar_date_picker2: ^1.1.7
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_advanced_switch: ^3.1.0
  permission_handler: ^11.0.1
  image_cropper: ^6.0.0
  camera: ^0.10.5+9
  image: ^4.5.2
  image_picker: ^1.0.8
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
